import { calculateVulnerability, DEFAULT_SCORING_WEIGHTS } from "./scoring";

export const BASELINE_SETTLEMENTS = [
  {
    id: "tn-ram-01",
    name: "Mandapam Coastal Habitation",
    code: "TN-RAM-01",
    block: "Mandapam",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.2783,
    longitude: 79.1245,
    population: 18200,
    populationYear: 2011,
    populationDensity: 420.0,
    waterAccessPct: 32.5,
    waterSourceType: "Combined Water Supply Scheme (CWSS) & RO Kiosk",
    waterServiceLevel: "Limited Piped Supply",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 48.0,
    sanitationServiceType: "Individual Household Latrine (IHHL)",
    sanitationReferenceYear: 2024,
    povertyRate: 54.2,
    rainfallAnnualMm: 820,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 4,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 38.0,
    waterPointsCount: 24,
    functioningWaterPointsCount: 13,
    sanitationFacilitiesCount: 6,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 68.3,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 1, fieldVerifications: 1, alerts: 2 },
  },
  {
    id: "tn-ram-02",
    name: "Tiruvadanai Agrarian Panchayat",
    code: "TN-RAM-02",
    block: "Tiruvadanai",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.7891,
    longitude: 78.9124,
    population: 24500,
    populationYear: 2011,
    populationDensity: 310.0,
    waterAccessPct: 38.0,
    waterSourceType: "Deep Borewell with OHT & Open Ooranis",
    waterServiceLevel: "Unimproved / High Total Dissolved Solids",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 52.0,
    sanitationServiceType: "Twin-Pit Pour Flush Latrine",
    sanitationReferenceYear: 2024,
    povertyRate: 58.0,
    rainfallAnnualMm: 890,
    floodHazardLevel: "High",
    historicalFloodEvents: 3,
    infrastructureScore: 42.0,
    waterPointsCount: 32,
    functioningWaterPointsCount: 19,
    sanitationFacilitiesCount: 8,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 62.6,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 0, fieldVerifications: 0, alerts: 2 },
  },
  {
    id: "tn-ram-03",
    name: "Mudukulathur Drought Basin",
    code: "TN-RAM-03",
    block: "Mudukulathur",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.3421,
    longitude: 78.5123,
    population: 29800,
    populationYear: 2011,
    populationDensity: 295.0,
    waterAccessPct: 29.0,
    waterSourceType: "Cauvery Integrated Pipeline Extension",
    waterServiceLevel: "Intermittent Tank Supply",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 44.0,
    sanitationServiceType: "Individual Household Latrine (IHHL)",
    sanitationReferenceYear: 2024,
    povertyRate: 62.5,
    rainfallAnnualMm: 740,
    floodHazardLevel: "Moderate",
    historicalFloodEvents: 1,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 32.0,
    waterPointsCount: 38,
    functioningWaterPointsCount: 16,
    sanitationFacilitiesCount: 5,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 63.2,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 0, fieldVerifications: 0, alerts: 1 },
  },
  {
    id: "tn-ram-04",
    name: "Kilakarai Coastal Habitation",
    code: "TN-RAM-04",
    block: "Kilakarai",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.2312,
    longitude: 78.7845,
    population: 38400,
    populationYear: 2011,
    populationDensity: 850.0,
    waterAccessPct: 45.0,
    waterSourceType: "Desalination Plant & TWAD Piped Feed",
    waterServiceLevel: "Basic Piped Connection",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 64.0,
    sanitationServiceType: "Septic Tank with Soak Pit",
    sanitationReferenceYear: 2024,
    povertyRate: 41.0,
    rainfallAnnualMm: 860,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 3,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 54.0,
    waterPointsCount: 42,
    functioningWaterPointsCount: 31,
    sanitationFacilitiesCount: 14,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 59.0,
    vulnerabilityCategory: "MODERATE",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 0, fieldVerifications: 0, alerts: 1 },
  },
  {
    id: "tn-ram-05",
    name: "Paramakudi Riverine Cluster",
    code: "TN-RAM-05",
    block: "Paramakudi",
    district: "Ramanathapuram",
    state: "Tamil Nadu",
    country: "India",
    latitude: 9.5432,
    longitude: 78.5912,
    population: 52000,
    populationYear: 2011,
    populationDensity: 620.0,
    waterAccessPct: 56.0,
    waterSourceType: "Vaigai River Bed Subsurface Collector Well",
    waterServiceLevel: "Basic",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 61.0,
    sanitationServiceType: "Piped Sewerage / Septic",
    sanitationReferenceYear: 2024,
    povertyRate: 46.0,
    rainfallAnnualMm: 810,
    floodHazardLevel: "High",
    historicalFloodEvents: 2,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 61.0,
    waterPointsCount: 56,
    functioningWaterPointsCount: 44,
    sanitationFacilitiesCount: 18,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 53.2,
    vulnerabilityCategory: "MODERATE",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 0, fieldVerifications: 0, alerts: 1 },
  },
  {
    id: "tn-cud-06",
    name: "Parangipettai Estuary Village",
    code: "TN-CUD-06",
    block: "Parangipettai",
    district: "Cuddalore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.4982,
    longitude: 79.7645,
    population: 32500,
    populationYear: 2011,
    populationDensity: 690.0,
    waterAccessPct: 41.0,
    waterSourceType: "Vellar River Subsurface Infiltration Scheme",
    waterServiceLevel: "Limited / Estuary Saline Intrusion",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 50.0,
    sanitationServiceType: "IHHL & Community Complex",
    sanitationReferenceYear: 2024,
    povertyRate: 51.5,
    rainfallAnnualMm: 1350,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 5,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 40.0,
    waterPointsCount: 36,
    functioningWaterPointsCount: 21,
    sanitationFacilitiesCount: 9,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 65.7,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 1, fieldVerifications: 1, alerts: 2 },
  },
  {
    id: "tn-cud-07",
    name: "Chidambaram Rural Habitations",
    code: "TN-CUD-07",
    block: "Chidambaram",
    district: "Cuddalore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.3991,
    longitude: 79.6934,
    population: 46200,
    populationYear: 2011,
    populationDensity: 740.0,
    waterAccessPct: 58.0,
    waterSourceType: "Kollidam River Deep Borewell Collector Wells",
    waterServiceLevel: "Basic Tap Water",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 62.0,
    sanitationServiceType: "Pour-Flush Septic System",
    sanitationReferenceYear: 2024,
    povertyRate: 45.0,
    rainfallAnnualMm: 1280,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 4,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 58.0,
    waterPointsCount: 52,
    functioningWaterPointsCount: 42,
    sanitationFacilitiesCount: 16,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 56.6,
    vulnerabilityCategory: "MODERATE",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 0, fieldVerifications: 0, alerts: 1 },
  },
  {
    id: "tn-cud-08",
    name: "Kurinjipadi Inland Panchayat",
    code: "TN-CUD-08",
    block: "Kurinjipadi",
    district: "Cuddalore",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.5643,
    longitude: 79.6012,
    population: 35400,
    populationYear: 2011,
    populationDensity: 480.0,
    waterAccessPct: 53.0,
    waterSourceType: "Cuddalore Sandstone Deep Aquifer",
    waterServiceLevel: "Basic",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 58.0,
    sanitationServiceType: "Twin-Pit Latrine",
    sanitationReferenceYear: 2024,
    povertyRate: 48.0,
    rainfallAnnualMm: 1150,
    floodHazardLevel: "Moderate",
    historicalFloodEvents: 2,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 52.0,
    waterPointsCount: 40,
    functioningWaterPointsCount: 30,
    sanitationFacilitiesCount: 11,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 50.5,
    vulnerabilityCategory: "MODERATE",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 0, fieldVerifications: 0, alerts: 0 },
  },
  {
    id: "tn-nag-09",
    name: "Vedaranyam Salt Pan Panchayat",
    code: "TN-NAG-09",
    block: "Vedaranyam",
    district: "Nagapattinam",
    state: "Tamil Nadu",
    country: "India",
    latitude: 10.3721,
    longitude: 79.8512,
    population: 34200,
    populationYear: 2011,
    populationDensity: 510.0,
    waterAccessPct: 26.0,
    waterSourceType: "Deep Sand Dune Freshwater Lenses & Tankers",
    waterServiceLevel: "Unimproved / Highly Saline",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 41.0,
    sanitationServiceType: "Individual Household Latrine",
    sanitationReferenceYear: 2024,
    povertyRate: 64.0,
    rainfallAnnualMm: 1420,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 6,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 28.0,
    waterPointsCount: 30,
    functioningWaterPointsCount: 11,
    sanitationFacilitiesCount: 5,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 74.3,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 1, fieldVerifications: 1, alerts: 2 },
  },
  {
    id: "tn-may-10",
    name: "Tharangambadi Coastal Hamlet",
    code: "TN-MAY-10",
    block: "Tharangambadi",
    district: "Mayiladuthurai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 11.0289,
    longitude: 79.8543,
    population: 27800,
    populationYear: 2011,
    populationDensity: 650.0,
    waterAccessPct: 48.0,
    waterSourceType: "Cauvery Tail-End CWSS Pipeline",
    waterServiceLevel: "Limited",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 56.0,
    sanitationServiceType: "Pour-Flush to Septic",
    sanitationReferenceYear: 2024,
    povertyRate: 47.0,
    rainfallAnnualMm: 1310,
    floodHazardLevel: "Severe",
    historicalFloodEvents: 4,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 49.0,
    waterPointsCount: 35,
    functioningWaterPointsCount: 24,
    sanitationFacilitiesCount: 10,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 61.0,
    vulnerabilityCategory: "HIGH",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 0, fieldVerifications: 0, alerts: 2 },
  },
  {
    id: "tn-dha-11",
    name: "Pennagaram Fluorosis Belt",
    code: "TN-DHA-11",
    block: "Pennagaram",
    district: "Dharmapuri",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.1342,
    longitude: 77.8921,
    population: 38900,
    populationYear: 2011,
    populationDensity: 390.0,
    waterAccessPct: 36.0,
    waterSourceType: "Hogenakkal Drinking Water Fluorosis Mitigation Scheme",
    waterServiceLevel: "Treated Fluoride-Safe Tap Water",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 49.0,
    sanitationServiceType: "IHHL Rural Latrine",
    sanitationReferenceYear: 2024,
    povertyRate: 59.0,
    rainfallAnnualMm: 850,
    floodHazardLevel: "Low",
    historicalFloodEvents: 0,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 44.0,
    waterPointsCount: 44,
    functioningWaterPointsCount: 26,
    sanitationFacilitiesCount: 9,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 53.0,
    vulnerabilityCategory: "MODERATE",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 1, fieldVerifications: 0, alerts: 0 },
  },
  {
    id: "tn-tir-12",
    name: "Polur Hard-Rock Habitation",
    code: "TN-TIR-12",
    block: "Polur",
    district: "Tiruvannamalai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.5123,
    longitude: 79.1245,
    population: 31500,
    populationYear: 2011,
    populationDensity: 440.0,
    waterAccessPct: 42.0,
    waterSourceType: "Cheyyar River Infiltration & Borewells",
    waterServiceLevel: "Basic Tap Water",
    waterDataConfidence: "Official / JJM WQMIS",
    waterReferenceYear: 2024,
    sanitationAccessPct: 51.0,
    sanitationServiceType: "Individual Household Latrine",
    sanitationReferenceYear: 2024,
    povertyRate: 53.0,
    rainfallAnnualMm: 1020,
    floodHazardLevel: "Moderate",
    historicalFloodEvents: 1,
    climateReferencePeriod: "IMD Climatology / CWC Atlas",
    infrastructureScore: 50.0,
    waterPointsCount: 39,
    functioningWaterPointsCount: 27,
    sanitationFacilitiesCount: 11,
    infrastructureStatus: "Reported by TWAD / Gram Panchayat",
    compositeVulnerabilityScore: 55.5,
    vulnerabilityCategory: "MODERATE",
    dataCompletenessPct: 100,
    sourceStatus: "Demo",
    isSampleData: true,
    status: "ACTIVE",
    _count: { interventions: 0, fieldVerifications: 0, alerts: 0 },
  },
];

export function getFallbackAnalyticsResponse() {
  const communities = BASELINE_SETTLEMENTS;
  const analyzedCommunitiesCount = communities.length;
  let totalPopulation = 0;
  let populationInadequateWater = 0;
  let populationInadequateSanitation = 0;
  let highVulnerabilityCount = 0;
  let significantFloodExposureCount = 0;

  const districtMap: Record<string, any> = {};

  for (const c of communities) {
    totalPopulation += c.population;
    populationInadequateWater += Math.round(c.population * (1 - c.waterAccessPct / 100));
    populationInadequateSanitation += Math.round(c.population * (1 - c.sanitationAccessPct / 100));
    if (c.compositeVulnerabilityScore >= 60) highVulnerabilityCount++;
    if (["High", "Severe"].includes(c.floodHazardLevel)) significantFloodExposureCount++;

    const d = c.district;
    if (!districtMap[d]) {
      districtMap[d] = {
        district: d,
        state: c.state,
        region: d,
        communitiesCount: 0,
        population: 0,
        totalWater: 0,
        totalSanitation: 0,
        totalVuln: 0,
      };
    }
    districtMap[d].communitiesCount++;
    districtMap[d].population += c.population;
    districtMap[d].totalWater += c.waterAccessPct;
    districtMap[d].totalSanitation += c.sanitationAccessPct;
    districtMap[d].totalVuln += c.compositeVulnerabilityScore;
  }

  const districtStats = Object.values(districtMap).map((d: any) => ({
    district: d.district,
    state: d.state,
    region: d.district,
    communitiesCount: d.communitiesCount,
    population: d.population,
    averageWaterAccess: Math.round(d.totalWater / d.communitiesCount),
    averageSanitationAccess: Math.round(d.totalSanitation / d.communitiesCount),
    averageVulnerability: Math.round(d.totalVuln / d.communitiesCount),
  }));

  const vulnerabilityDistribution = [
    { category: "HIGH", count: 7 },
    { category: "MODERATE", count: 5 },
  ];

  const riskFactorAverages = [
    { name: "Water Access Gap (JJM Tap Coverage)", averageScore: 59, weight: 25, color: "#06b6d4", source: "Jal Jeevan Mission / WQMIS" },
    { name: "Sanitation Access Gap (SBM-G Coverage)", averageScore: 48, weight: 20, color: "#3b82f6", source: "Swachh Bharat Mission (Grameen)" },
    { name: "Climate & Flood Exposure (IMD & CWC)", averageScore: 71, weight: 20, color: "#f97316", source: "India Meteorological Dept / CWC" },
    { name: "Socioeconomic Deprivation (NFHS-5)", averageScore: 53, weight: 15, color: "#eab308", source: "NFHS-5 (2019-2021) / NITI Aayog" },
    { name: "Infrastructure Fragility (TWAD Board)", averageScore: 56, weight: 10, color: "#ef4444", source: "Tamil Nadu Water Supply & Drainage Board" },
    { name: "Population Vulnerability (Census 2011)", averageScore: 42, weight: 10, color: "#8b5cf6", source: "Census of India 2011" },
  ];

  return {
    success: true,
    timestamp: new Date().toISOString(),
    summary: {
      analyzedCommunitiesCount,
      totalPopulation,
      populationInadequateWater,
      populationInadequateSanitation,
      highVulnerabilityCount,
      significantFloodExposureCount,
      incompleteDatasetsCount: 0,
      pendingVerifications: 3,
      activeInterventions: 3,
      totalInterventions: 4,
      activeAlerts: 6,
    },
    vulnerabilityDistribution,
    regionalStats: districtStats,
    districtStats,
    riskFactorAverages,
    recentAssessments: [],
  };
}
